"""update id column type in posts table

Revision ID: 2f35728f0fe9
Revises: c8b3e43e556e
Create Date: 2024-10-02 14:35:07.503300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f35728f0fe9'
down_revision: Union[str, None] = 'c8b3e43e556e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
